acc: Unset all env vars in inprocess mode (#2822)
## Why
We need to cleanup existing env vars in the parent CLI process in
inprocess mode. Just setting new environment variables is not enough.
This was noticed in https://github.com/databricks/cli/pull/2720 and is
necessarily for it to work since otherwise we end up with conflicting
auth.

## Tests
Manually, before local tests would fail when non PAT auth was configured
in terminal, for example `selftest/server` fails with when OAuth is
configured:
```
Error: inner token: Post "[UUID]/oauth2/token": Post "[UUID]/oauth2/token": unsupported protocol scheme ""
```

Now these local tests pass.