Configuration for git to ignore generated test output on rebase/merge (#3773)
## Why
Having output file in conflicted state requires marking them as resolve
manually which adds to rebase/merge toil. You're going to regenerate
them anyway, so no need to spend time on these conflicts.

## Tests
Manually, by creating a conflicting change in script & output.txt:

```
% git rebase -i a
Auto-merging acceptance/selftest/basic/output.txt
Auto-merging acceptance/selftest/basic/script
CONFLICT (content): Merge conflict in acceptance/selftest/basic/script
error: could not apply 73b9af638... update Y
...
Could not apply 73b9af638... # update Y
```