tweak selftest/timeout on windows
          	Error:      	Not equal:
          	            	expected: "\n>>> sleep 2\n\nError: Test script killed due to a timeout\n"
          	            	actual  : "\nError: Test script killed due to a timeout\n"

          	            	Diff:
          	            	--- Expected
          	            	+++ Actual
          	            	@@ -1,3 +1 @@
          	            	-
          	            	->>> sleep 2