direct: retry 504 errors (#5349)
## Changes
Retry resource methods that return an error that has http_code equal to
504 but that has not been retried by SDK.

This affects all DoRead, DoUpdate(WithID), DoDelete. This affects
DoCreate for grants and permissions.

Note, for DoCreate the retry functionality is opt-in - implementations
need to wrap error with retrySafe(). For other methods the retry is
always enabled.

## Why
We've seen reports where deploy fails with 
> Error: cannot create resources.pipelines.<pipeline>.permissions: The
service at /api/2.0/permissions/pipelines/<pipeline_id> is taking too
long to process your request. (504 TEMPORARILY_UNAVAILABLE)

We also saw that terraform does custom retries for 504/GET
https://github.com/databricks/terraform-provider-databricks/pull/4355

Note, the two cases are different - the first one is "cannot create" so
it refers to PUT.

## Tests
New testserver feature that allows injecting expiring faults in a given
endpoint. See fault.py.
New acceptance tests make use of fault.py to check failures in
plan/create/update for permissions.