Include [DEFAULT] section header when writing ~/.databrickscfg
The ini library omits the default section header and in doing so
breaks compatibility with Python's config parser. It raises:

```
Error: MissingSectionHeaderError: File contains no section headers.
```

This commit makes sure the DEFAULT section header is included.

If the config file doesn't include a DEFAULT section itself,
we include a comment describing its purpose.