Apply upstream genkit fix to warehouses update-default-warehouse-override (#5079)
## Changes
Apply upstream genkit fix to warehouses
update-default-warehouse-override

Only added the affected file updated by `make generate`, did not include
other changes (can wait till next SDK bump).

**Additional Makefile changes**
- Allow skipping checkout (by default it checks out the sha, which means
you can't apply current fixes without going through the whole SDK bump
flow)
- Bail if universe is dirty before checkout (if you have uncommitted
changes in universe from experimentation, it might end up in the `make
generate` flow)

With dirty universe:
```
$ echo aaa >> ../universe/README.md
$ make generate
Error: universe repo at /home/jan.rose/universe has uncommitted changes; commit or stash them, or set UNIVERSE_SKIP_CHECKOUT=1 to skip checkout
make: *** [Makefile:210: generate] Error 1
```

With universe checked out at master (which contains the fix):
```
$ UNIVERSE_SKIP_CHECKOUT=1 make generate
UNIVERSE_SKIP_CHECKOUT set; using current /home/jan.rose/universe HEAD
Building genkit...
```

## Why
Fixes #5070 

## Tests
```
% make build
go mod tidy
go build

% ./cli warehouses update-default-warehouse-override
Error: accepts 3 arg(s), received 0                    <--------- not panic like in issue #5070 

Usage:
  databricks warehouses update-default-warehouse-override NAME UPDATE_MASK TYPE [flags]
[...]

% ./cli warehouses update-default-warehouse-override foo bar baz
Error: Not Found

% ID=$(./cli warehouses list-default-warehouse-overrides | jq -r '.[0].name')
% ./cli warehouses update-default-warehouse-override ${ID} '*' 'LAST_SELECTED'
{
  "default_warehouse_override_id":"70414931314098",
  "name":"default-warehouse-overrides/70414931314098",
  "type":"LAST_SELECTED"
}
```