Error when bundle root path contains glob (#3096)
## Changes
This PR adds an error when the bundle root path contains a glob
character.

```
Error: Bundle root path contains glob pattern characters

The path to the bundle root [TEST_TMP_DIR]/[abc] contains glob pattern character "[". Please remove the character from this path to use bundle commands.


Found 1 error
```

## Why
We provide full paths to `filepath.Glob` to figure out which paths to
include. If the file path itself happens to contain a glob pattern, then
`filepath.Glob` interprets that as a glob pattern, even though we should
not be parsing glob patterns there.

Escaping those glob patterns is also not possible because escaping is
not supported on windows. ref: https://pkg.go.dev/path/filepath#Match

Thus, we error here to inform users to modify their root paths before
doing a bundle deployment.

Note:
1. We could support this but that would mean writing our own glob
function. We can use the `filepath.Match` function to match the patterns
themselves but we would have to walk the paths. The ROI for this option
is low at the moment because our custom function would have to have the
same semantics as the `filepath.Glob` function which would take some
time to get right.
2. This PR does not completely solve the problem since there are some
other places as well where glob patterns might be accidentally parsed.
However, this PR addresses the most important usecase i.e. making during
the `includes` are correct and complete. Other usecases like libraries
not being uploaded correctly are less important and even those will be
very likely caught by this PR unless the user only has a single
`databricks.yml` in their bundle. refs:
https://github.com/databricks/cli/blob/d177292b5b2e5ce779c5d6c5d42feeec00cc533a/bundle/artifacts/expand_globs.go#L68

https://github.com/databricks/cli/blob/d177292b5b2e5ce779c5d6c5d42feeec00cc533a/bundle/libraries/expand_glob_references.go#L42

## Tests
New unit and acceptance tests.