acc: Do not auto enable EnvRepl for short strings
Mainly to exclude "yes" and "no" in templates tests that cause messages like this:

  Error: can[SERVERLESS]t create pipeline: The service at /api/2.0/pipelines is taking too long to process your request.