Do not add 'development' in generated pipeline configuration (#3824)
## Changes
Do not add 'development' in the generated pipeline configuration

## Why
This field is specific to the mode in which the pipeline is running and
can be irrelevant for the generated config.
Otherwise it is possible to run into the issues like
```
Error: target with 'mode: production' cannot include a pipeline with 'development: true'
```

## Tests
Exisiting acceptance test pass

<!-- If your PR needs to be included in the release notes for next
release,
add a separate entry in NEXT_CHANGELOG.md as part of your PR. -->