acc: Use unique name in deploy/empty-bundle (#3324)
Otherwise there are conflicts when running on cloud.

```
Error: Failed to acquire deployment lock: deploy lock acquired by [USERNAME] at [TIMESTAMP].[NUMID] +0000 UTC. Use --force-lock to override
Error: deploy lock acquired by [USERNAME] at [TIMESTAMP].[NUMID] +0000 UTC. Use --force-lock to override
```