Implement synced_database_table in direct deployment (#3525)
## Why
<!-- Why are these changes needed? Provide the context that the reviewer
might be missing.
For example, were there any decisions behind the change that are not
reflected in the code itself? -->

- This change allows to deploy database catalogs when using direct-exp
deployment method

## Tests
<!-- How have you tested the changes? -->

Important notice: destroying a bundle with a synced database table in it
fails when using `direct-exp` method with the following error:

```
Error: cannot delete synced_database_tables.my_synced_table: deleting id=my_catalog_[UNIQUE_NAME].my_database.my_synced_table: Catalog 'my_catalog_[UNIQUE_NAME]' does not exist. (404 CATALOG_DOES_NOT_EXIST)

        Endpoint: DELETE [DATABRICKS_URL]/api/2.0/database/synced_tables/my_catalog_[UNIQUE_NAME].my_database.my_synced_table?
        HTTP Status: 404 Not Found
        API error_code: CATALOG_DOES_NOT_EXIST
        API message: Catalog 'my_catalog_[UNIQUE_NAME]' does not exist.
```

`direct-exp` method currently does not support waiting for deletion,
thus the tests for `direct-exp` are currently not enabled

<!-- If your PR needs to be included in the release notes for next
release,
add a separate entry in NEXT_CHANGELOG.md as part of your PR. -->