Make apply_presets.go more resilient and consistent (#2777)
## Changes
Modify ApplyPresets to never return errors and instead create necessary
inner struct (unless full resource is declared as null).

## Why
The errors that it returned were not very helpful:

```
Error: dashboard set_to_true s is not defined
```
(If there are some required fields missing, we should have validators
specifically for that).

Besides bad error message other issues were:
- Checking embedded pointer is not helpful, that could be empty if only
fields on the outside struct are set.
- Checking outer pointer was often omitted, giving a possibility of a
crash.

This made ApplyPresets behave different for different resources
depending on whether those resources have default. If they have a
default (e.g. dashboards), then those defaults would initialize embedded
struct and ApplyPresets would work. Otherwise it would complain. This
inconsistency would prevent moving ApplyPresets to run before defaults,
see https://github.com/databricks/cli/pull/2778.

## Tests
Tests added previously in https://github.com/databricks/cli/pull/2771
and https://github.com/databricks/cli/pull/2774