Encode Python 3.12 requirement in PEP-723 block (#3445)
## Why

I tried running `gh_report.py` with system Python and it failed with:
```
AttributeError: 'PosixPath' object has no attribute 'walk'
```

This was added in Python 3.12.

## Tests

I can now run the script through `uv run`.