Fix error propogation in the `bundle generate dashboard` command (#3354)
## Changes
Fixes a regression introduced in
https://github.com/databricks/cli/pull/3175, where the errors in these
functions would be dropped instead of being propagated. I noticed this
regression while updating the CLI dashboard.

This also highlights the downside returning diagnostics and using
`logdiag` to log it later, outside mutators, since a linter would have
caught it otherwise.

## Tests
Added regression test. Also manually:

Before:
```
➜  cli_telemetry_dashboard git:(main) databricks bundle generate dashboard --resource cli_telemetry -p logfood        
➜  cli_telemetry_dashboard git:(main) git status                     
On branch main
Your branch is up to date with 'origin/main'.
```

After:
```
➜  cli_telemetry_dashboard git:(main) cli bundle generate dashboard --resource cli_telemetry -p logfood        
Error: src/cli_telemetry.lvdash.json already exists. Use --force to overwrite
```

Ideally, we would not use logdiag here and instead refactor these and
other functions like these to return errors. It's out of scope for me
for now.