direct: Generate resources config based on OpenAPI field behaviours (#4391)
## Changes
- New script bundle/direct/tools/generate_apitypes.py to find API type
for each resource.
- New script bundle/direct/tools/generate_resources.py to generate
resources.generated.yml
- Bundle plan is updated to consult resources.yml first then fallback to
generated one.
- New make command: 'make generate-direct' to update everything.

## Why
This adds a lot of input_only, output_only fields. Many of the fields
matching are currently ignored via "server_side_default" reason. This PR
allows removing that eventually.

## Tests
I removed server_side_default field on main and this branch and compared
invariant/no_drift tests results on testserver:

On main:

```
        --- FAIL: TestAccept/bundle/invariant/no_drift/DATABRICKS_BUNDLE_ENGINE=direct/INPUT_CONFIG=alert.yml.tmpl (1.63s)
        --- FAIL: TestAccept/bundle/invariant/no_drift/DATABRICKS_BUNDLE_ENGINE=direct/INPUT_CONFIG=job.yml.tmpl (1.64s)
        --- FAIL: TestAccept/bundle/invariant/no_drift/DATABRICKS_BUNDLE_ENGINE=direct/INPUT_CONFIG=database_catalog.yml.tmpl (1.65s)
        --- FAIL: TestAccept/bundle/invariant/no_drift/DATABRICKS_BUNDLE_ENGINE=direct/INPUT_CONFIG=volume.yml.tmpl (1.65s)
        --- FAIL: TestAccept/bundle/invariant/no_drift/DATABRICKS_BUNDLE_ENGINE=direct/INPUT_CONFIG=model_serving_endpoint.yml.tmpl (1.65s)
        --- FAIL: TestAccept/bundle/invariant/no_drift/DATABRICKS_BUNDLE_ENGINE=direct/INPUT_CONFIG=app.yml.tmpl (1.66s)
        --- FAIL: TestAccept/bundle/invariant/no_drift/DATABRICKS_BUNDLE_ENGINE=direct/INPUT_CONFIG=synced_database_table.yml.tmpl (1.66s)
        --- FAIL: TestAccept/bundle/invariant/no_drift/DATABRICKS_BUNDLE_ENGINE=direct/INPUT_CONFIG=database_instance.yml.tmpl (1.67s)
        --- FAIL: TestAccept/bundle/invariant/no_drift/DATABRICKS_BUNDLE_ENGINE=direct/INPUT_CONFIG=registered_model.yml.tmpl (1.67s)
        --- FAIL: TestAccept/bundle/invariant/no_drift/DATABRICKS_BUNDLE_ENGINE=direct/INPUT_CONFIG=pipeline.yml.tmpl (1.67s)
```

on this branch:

```
        --- FAIL: TestAccept/bundle/invariant/no_drift/DATABRICKS_BUNDLE_ENGINE=direct/INPUT_CONFIG=registered_model.yml.tmpl (1.04s)
        --- FAIL: TestAccept/bundle/invariant/no_drift/DATABRICKS_BUNDLE_ENGINE=direct/INPUT_CONFIG=job.yml.tmpl (1.05s)
        --- FAIL: TestAccept/bundle/invariant/no_drift/DATABRICKS_BUNDLE_ENGINE=direct/INPUT_CONFIG=model_serving_endpoint.yml.tmpl (1.06s)
        --- FAIL: TestAccept/bundle/invariant/no_drift/DATABRICKS_BUNDLE_ENGINE=direct/INPUT_CONFIG=pipeline.yml.tmpl (1.07s)
        --- FAIL: TestAccept/bundle/invariant/no_drift/DATABRICKS_BUNDLE_ENGINE=direct/INPUT_CONFIG=volume.yml.tmpl (1.09s)
```

So it fixes 5 no_drift tests: alerts, database_catalog, app,
synced_database_table, database_instance

---------

Co-authored-by: Claude <noreply@anthropic.com>