Fix TestLock not to create a new repo (#3201)
## Why
This integration test creates a repo when it does not need to. Repos
have been a persistent source of flakiness because they do not behave
well under load.

This PR reduces flakiness and improves CI health. 
 
Failure logs:
```
=== FAIL: integration/libs/git TestFetchRepositoryInfoAPI_FromRepo (re-run 2) (4.42s)
        	Error:      	Received unexpected error:
        	            	a Workspace object at path /Repos/***/integration-test-e7844b5d8018420996b3bb0f95aec84e already exists. Try a different path for your Repo or rename the existing Workspace object.
```