Pass through OIDC token env variable to Terraform (#3113)
## Changes
Pass through OIDC token env variable to Terraform

## Why
This allows OIDC auth to correctly work in DABs, otherwise it fails with
```
Error: cannot create job: failed during request visitor: env-oidc auth: missing env var "DATABRICKS_OIDC_TOKEN". Config: host=*** client_id=***. Env: DATABRICKS_HOST, DATABRICKS_CLIENT_ID
```

## Tests
Added unit test

<!-- If your PR needs to be included in the release notes for next
release,
add a separate entry in NEXT_CHANGELOG.md as part of your PR. -->